CREATE USER 'beyar'@'%' IDENTIFIED BY '...';
CREATE USER 'olof'@'%' IDENTIFIED BY '...';

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'beyar'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'olof'@'%';

GRANT SELECT, INSERT ON Library.* TO 'beyar'@'%';
GRANT SELECT, INSERT ON Library.* TO 'olof'@'%';

FLUSH PRIVILEGES;

SHOW GRANTS FOR 'beyar'@'%';
SHOW GRANTS FOR 'olof'@'%';
